variable "region" {}
variable "pipeline_name" {}
variable "codebuild_name" {}
variable "build_path" {}
variable "code_repository_url" {}
variable "codestar_connection_name" {}
variable "codestar_provider_type" {}
variable "key_id" {}
variable "key_arn" {}
variable "sns_name" {}
variable "sns_update_name" {}
variable "sns_update_arn" {}
variable "bucket_name" {}
variable "sns_endpoint" {}
variable "tf_code_deployment_name" {}
variable "pipeline_name_arn" {}
variable "codebuild_project_arn" {}
variable "bucket_id" {}
variable "bucket_arn" {}